server:
  port: 9003

spring:
  application:
    name: MESSAGE-SERVICE
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/messagedb
    password: sa123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "*"
        allowedHeaders: "*"
        allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE

openapi:
  service:
    title: MessageService APIs
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /message-service/v3/api-docs
  swagger-ui:
    path: /message-service/swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
