server:
  port: 9002

spring:
  codec:
    max-in-memory-size: 10MB
  application:
    name: POST-SERVICE
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postdb
    password: sa123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: validate
    show-sql: 'true'
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "*"
        allowedHeaders: "*"
        allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE
  flyway:
    baseline-on-migrate: true
  batch:
    jdbc:
      initialize-schema: "always"
    job:
      enabled: false

openapi:
  service:
    title: PostService APIs
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /post-service/v3/api-docs
  swagger-ui:
    path: /post-service/swagger-ui.html

flyway:
  url: jdbc:postgresql://localhost:5432/postdb
  schemas: POSTSERVICE
  user: postgres
  password: sa123

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

cloudinary:
  cloud_name: minh2212
  api_key: 689138855327619
  api_secret: lvuOh4BHRyVcvy_8FCeVpC-G9a0