server:
  port: 0

spring:
  application:
    name: POST_SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/
  instance:
    preferIpAddress: true