server:
  port: 9002

spring:
  application:
    name: POST-SERVICE
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postdb
    password: sa123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "*"
        allowedHeaders: "*"
        allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true