server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**, /friend/**
        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post/**, /comment/**
        - id: MESSAGE-SERVICE
          uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/message/**, /ws/**, /conversation/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
  codec:
    max-in-memory-size: 10MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /post-service/v3/api-docs
        name: Post Service
        primaryName: Post Service
      - url: /friend-service/v3/api-docs
        name: Friend Service
        primaryName: Friend Service
      - url: /message-service/v3/api-docs
        name: Message Service
        primaryName: Message Service